source "https://rubygems.org"

gem "middleman"
gem "middleman-livereload"
gem "middleman-deploy"
gem "middleman-blog"
gem "middleman-protect-emails"
gem "middleman-syntax"
gem "middleman-title"
gem "middleman-google-analytics"
gem "bourbon"
gem "neat"
